config/routes.rb
Rails.application.routes.draw do

  ##
  # Messing around with Administrate but I don't think it's going
  # to play well with refile and our image uploading requirements
  # namespace :admin do
  #   DashboardManifest::DASHBOARDS.each do |dashboard_resource|
  #     resources dashboard_resource
  #   end
  #   root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  # end

  resources :images
  resources :sessions, only: [:create, :destroy]
  get 'grid' => 'welcome#grid', as: :browse_grid

  get 'license' => 'welcome#license'
  get 'terms'   => 'welcome#terms'
  get 'privacy' => 'welcome#privacy'
  get 'contact' => 'welcome#contact'
  post 'subscribe' => 'welcome#subscribe', as: :subscribe_user
  root 'welcome#index'

end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                      :integer          not null, primary key
#  title                   :string(255)
#  description             :text(65535)
#  status                  :integer
#  image_data_id           :string(255)
#  image_data_filename     :string(255)
#  image_data_size         :integer
#  image_data_content_type :string(255)
#  license_id              :integer
#  metadata                :text(65535)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class Image < ActiveRecord::Base
  attachment :image_data

  def presigned_url(expires_in = 7.days)
    return nil if self.image_data_id.blank?
    obj = Aws::S3::Object.new(S3_CONFIG['bucket'], "#{S3_CONFIG['prefix']}/#{self.image_data_id}")
    obj.presigned_url(:get, response_content_disposition: 'attachment', expires_in: expires_in)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
class Admin::ApplicationController < Administrate::ApplicationController
  before_filter :authenticate_admin

  def authenticate_admin
    # TODO Add authentication logic here.
  end

  # Override this value to specify the number of elements to display at a time
  # on index pages. Defaults to 20.
  # def records_per_page
  #   params[:per_page] || 20
  # end
end

app/controllers/admin/images_controller.rb
module Admin
  class ImagesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Image.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Image.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin
    valid_user = authenticate_with_http_basic { |u, p| u == SETTINGS['admin_username'] && p == SETTINGS['admin_password'] }
    if valid_user
      return true
    else
      request_http_basic_authentication
    end
  end


end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:new, :create, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :description, :status, :remote_image_data_url, :image_data, :image_data_id, :image_data_size, :image_data_content_type, :image_data_filename, :license_id, :metadata)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create

  end

  def destroy

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    session[:token] ||= SecureRandom.hex[0,6].upcase
    @token = session[:token]
    @image = Image.first
  end

  def grid
    @images = Image.all
  end

  def license
  end

  def terms
  end

  def privacy
  end

  def contact
  end

  def subscribe
    @user = User.new(user_params)
    @user.save
    redirect_to browse_grid_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/images/_collection.html.erb
<%#
# Table

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `table_presenter`:
  An instance of [Administrate::Page::Table][1].
  The table presenter uses `ResourceDashboard::TABLE_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Table
%>

<table>
  <thead>
    <tr>
      <th clas="admin-image-thumb"></th>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label cell-label--<%= attr_type.html_class %>
          cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>
        ">
        <%= link_to(params.merge(
          collection_presenter.order_params_for(attr_name)
        )) do %>
            <%= attr_name.to_s.titleize %>

            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <%= inline_svg("administrate/sort_arrow.svg") %>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          data-url="<%= polymorphic_path([Administrate::NAMESPACE, resource]) -%>"
          >
        <td><%= attachment_image_tag(resource, :image_data, :fill, 120, 120, class: "img")%></td>
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <%= render_field attribute %>
          </td>
        <% end %>

        <td><%= link_to(
          t("administrate.actions.edit"),
          [:edit, Administrate::NAMESPACE, resource],
          class: "action-edit",
        ) %></td>

        <td><%= link_to(
          t("administrate.actions.destroy"),
          [Administrate::NAMESPACE, resource],
          class: "table__action--destroy",
          method: :delete,
          data: { confirm: t("administrate.actions.confirm") }
        ) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/images/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<%= form_for([Administrate::NAMESPACE, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(page.resource.errors.count, "error") %>
        prohibited this <%= page.resource_name %> from being saved:
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <% page.attributes.each do |attribute| -%>
      <div class="form-field form-field--<%= attribute.html_class %>">
        <%= render_field attribute, f: f %>
      </div>
    <% end -%>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/images/edit.html.erb
<%#
# Edit

This view is the template for the edit page.

It displays a header, and renders the `_form` partial to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "Edit #{page.page_title}" } %>

<header class="header">
  <h1 class="header-heading"><%= content_for(:title) %></h1>
  <%= link_to "Show #{page.resource}", [Administrate::NAMESPACE, page.resource], class: "button" %>
</header>

<%= render "form", page: page %>

app/views/admin/images/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Table][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Table
%>

<% content_for(:title) { page.resource_name.pluralize.titleize } %>

<% content_for(:search) do %>
  <form class="search">
    <span class="search__icon">
      <%= inline_svg "administrate/search.svg" %>
    </span>
    <input
      type="text"
      name="search"
      class="search__input"
      placeholder="Search"
      value="<%= search_term %>"
    />
    <span class="search__hint">
      Press enter to search
    </span>
  </form>
<% end %>

<header class="header">
  <h1 class="header-heading"><%= content_for(:title) %></h1>
  <%= link_to(
    "New #{page.resource_name.titleize.downcase}",
    [:new, Administrate::NAMESPACE, page.resource_name],
    class: "button",
  ) %>
</header>

<%= render "collection", collection_presenter: page, resources: resources %>

<%= paginate resources %>

app/views/admin/images/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) { "New #{page.resource_name.titleize}" } %>

<header class="header">
  <h1 class="header-heading"><%= content_for(:title) %></h1>
  <%= link_to 'Back', :back, class: "button" %>
</header>

<%= render 'form', page: page %>

app/views/admin/images/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { page.page_title } %>

<header class="header">
  <h1 class="header-heading"><%= content_for(:title) %></h1>
  <%= link_to(
    "Edit",
    [:edit, Administrate::NAMESPACE, page.resource],
    class: "button",
  ) %>
</header>

<dl>
  <% page.attributes.each do |attribute| %>
    <dt class="attribute-label"><%= attribute.name.titleize %></dt>

    <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
        ><%= render_field attribute %></dd>
  <% end %>
</dl>

app/views/images/_form.html.erb
<%= bootstrap_form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title %>
  <%= f.text_area :description %>
  <div class="form-group">
    <%= f.label :image_data, "Image file" %>
    <%= f.attachment_field :image_data, presigned: true, direct: true %>
  </div>
  <div class="actions">
    <%= f.submit "Create Image", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<% if notice %>
<p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>
<h1>Listing Images</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td>
          <%= link_to(attachment_image_tag(image, :image_data, :fill, 80, 80, class: "img"), image) %>
        </td>
        <td><%= image.title %></td>
        <td><%= image.description %></td>
        <td><%= image.status %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>
<%= render 'form' %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-8">
    <%= attachment_image_tag(@image, :image_data, :fit, 900, 900, class: "img img-responsive") %>
  </div>
  <div id="image-info" class="col-md-4">
    <h2><%= @image.title %></h2>
    <p>
      <strong>Description:</strong>
      <%= @image.description %>
    </p>

    <p>
      <strong>Status:</strong>
      <%= @image.status %>
    </p>

    <p>
      <strong>License:</strong>
      <%= @image.license_id %>
    </p>

    <p>
      <strong>Metadata:</strong>
      <%= @image.metadata %>
    </p>

    <p>

    </p>

    <p>
      <%= link_to @image.presigned_url, class: 'btn btn-primary btn-lg' do %>
        <i class="fa fa-cloud-download"></i>
        Download
      <% end %>
    </p>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= SETTINGS['site_name'] %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/masonry/3.3.2/masonry.pkgd.min.js" %>
  <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.2.0/imagesloaded.pkgd.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top-outer">
  <div id="top" class="container">
    <h1><%= link_to SETTINGS['site_name'], root_path %></h1>
  </div>
</div>
<div id="main" class="container">
  <%= yield %>
</div>
<div id="bottom-outer">
  <div id="bottom" class="container">
    <hr>
    <p>
      <strong>contact</strong> <%= mail_to SETTINGS['contact_email'] %>
    </p>
  </div>
</div>
</body>
</html>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/grid.html.erb
<div class="container">
  <% @images.in_groups_of(4, false) do |group| %>
  <div class="row grid-row">
    <% group.each do |image| %>
    <div class="col-md-3">
      <%= link_to(attachment_image_tag(image, :image_data, :fill, 600, 600, class: "img img-responsive"), image) %>
    </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1 class="text-center">Welcome</h1>
<p class="text-center">
  All images are licensed under a
  <a href="http://creativecommons.org/publicdomain/zero/1.0/">Creative Commons Zero license</a>
  and are free for personal and commercial use.
</p>
<hr>
<div class="row">
  <div class="col-md-6" style="min-height:400px;background-size:cover;background-image:url('<%= attachment_url(@image, :image_data, :fit, 1170, 1170) %>')">

  </div>
  <div class="col-md-6">
    <h2>Get Free Images</h2>
    <p>Subscribe to get notified when we release new, free images. We'll never share your information and you can unsubscribe at any time.</p>
    <%= bootstrap_form_for(User.new, url: subscribe_user_path) do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :email %>
      <%= f.submit "Continue" %>
    <% end %>
  </div>
</div>

app/views/welcome/license.html.erb
<h1>Welcome#license</h1>
<p>Find me in app/views/welcome/license.html.erb</p>

app/views/welcome/privacy.html.erb
<h1>Welcome#privacy</h1>
<p>Find me in app/views/welcome/privacy.html.erb</p>

app/views/welcome/terms.html.erb
<h1>Welcome#terms</h1>
<p>Find me in app/views/welcome/terms.html.erb</p>